* The Vision

"It's wine time.", says Liz to her husband Jack, meaning it is time to wrap up work and relax with a glass of wine and dinner in front of the TV.

"I'll see what *Argus* says about video possibilities while you pour the wine.", he replies.

Jack then brings up the *Argus* app on the first device that he finds, an iPad on the coffee table.  Using his Active List, Jack sees that the /Vikings/ is at the last episode of season five on Amazon and season four, episode one of /A Place to Call Home/ on Acorn TV is a good second choice for tonight's streaming pleasures.

While Liz is waiting for dinner to heat up she brings up *Argus* on her Pixel 3 XL phone and discovers on her list that /Poldark/ is now available on PBS.

So now it is settled, /Poldark/ series 5 episode 1 and /A Place to Call Home/ season four episode 1.

Jack switches to Liz's List on his iPad and chooses Watch from the /Poldark/ menu. The PBS app is started on the Living Room Chromecast and automagically selects the right episode. Jack hits pause to wait for Liz.

After dinner and a refresh on the merlot, Jack switches back to *Argus* with his list and selects the Watch menu item for /A Place to Call Home/. A new character appears shortly into the episode piqueing his curiosity, "where have we seen her before", he asks outloud.  Liz grabs her phone and switches to Jack's List and selects Episode Info menu item for /A Place to Call Home/. She taps on the Cast card and is presented with a list of actors and actresses for this episode. Recognizing the actress she clicks on the filmography link and quickly learns that it was Game of Thrones where the actress had a bit part.

And so it goes ...

* The Status

That short story was the vision that led to the *Argus* concept.  The complete realization of the vision is still a ways off but *Argus* does exist in the Android Play store (but not the App store yet) and new features are being added daily. Stay tuned ...
